server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///msaProject/git-local-repo
#          uri: file:///practice/git-local-repo

