server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
#          search-locations: file:///msaProject/native-file-repo
          search-locations: file:///practice/native-file-repo
        git:
          uri: https://github.com/rerun1129/spring-cloud-config.git
#          username:
#          password:
#          uri: file:///msaProject/git-local-repo
#          uri: file:///practice/git-local-repo

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
encrypt:
#  key: abcdefg0123456789
  key-store:
    location: file:///practice/keystore/apiEncryptionKey.jks
#    location: file:///msaProject/keystore/apiEncryptionKey.jks
    password: test1234
    alias: apiEncryptionKey